### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ixjlyons** [sixpearls/ndsplines#10]
Need to decide on a license.

Also need to decide how to give attribution for the `_bspl` module. I think adding their license to the file header, maybe a note about how they were modified, and adding a note to our own license file ([like SciPy does](https://github.com/scipy/scipy/blob/master/LICENSE.txt)) should be sufficient.

**Comment by sixpearls** [comment]
I tend to shy away from copy-left, and in particular I want to use this project for work. So BSD?

**Comment by ixjlyons** [comment]
:+1:
