### ISSUE TITLE
Packaging and distributing

### ISSUE THREAD

**Issue by ixjlyons** [sixpearls/ndsplines#18]
I was typing this up as a comment in #17 but thought it should go in its own issue.

The ideal option for users would be a wheel so they can just pip install in an empty venv and everything works. Second best would be an sdist so they have to have numpy and cython and a compiler installed first. There isn't really a way to set up the package so numpy/cython are installed automatically in order to build, as far as I know.

There will need to be separate wheels for different platforms, which makes that option a little painful to achieve for us. Azure Pipelines is something we've started using in a project I recently got involved in and it looks pretty great for having all-platform CI in one place. I believe it's pretty straightforward to temporarily store the build artifacts so they can be retrieved and then pushed to PyPI. It can probably also be automated so everything happens for you when you push a tag, but I haven't looked into it.

**Comment by ixjlyons** [comment]
Well, I guess there is this: https://github.com/Blosc/bcolz/blob/00044a1f26b174eef78bd46b8b36da90ee017173/setup.py#L34-L78

**Comment by sixpearls** [comment]
It looks like the recommendation may be to distribute the .c file ([SO snippet for ensuring the .c file is built when creating executing the sdist command](https://stackoverflow.com/a/18418524/854909)) and don't cythonize the `Extension`s. I think this resolves the Cython requirement for users.

I think requiring numpy to be installed and the system compiler to be setup before executing `pip install` for this package is reasonable given who I expect to use this.

We could also ship the pure numpy implementation to skip the build issues. I was kind of tempted to do that anyway so users could switch implementations if desired.

If you were motivated to setup a CI to build wheels that would be great. But in addition to supporting the different platforms, we would need to make sure we support the minor versions of python. Maybe it's not worth the hassle?

**Comment by sixpearls** [comment]
It looks like we could use the [`Feature`](https://stackoverflow.com/a/5735618) feature and/or possibly mark the pure C extension module [optional](https://docs.python.org/3/distutils/setupscript.html#other-options) so it is easy to `pip install` even without a compiler setup on the machine.

Then we can ship with the pure NumPy implementation and provide an API for switching between the C(ython) and NumPy implementations that defaults to the C(ython) version if it is available and the NumPy version if not.

**Comment by sixpearls** [comment]
Okay, I think this is closed by #20 (and #19). This should be `pip install`-able.
